export const icd10Codes = [
  // ===== Cardiovascular (20 codes) =====
  { code: 'I10', description: 'Essential (primary) hypertension', category: 'Cardiovascular' },
  { code: 'I11.9', description: 'Hypertensive heart disease without heart failure', category: 'Cardiovascular' },
  { code: 'I20.9', description: 'Angina pectoris, unspecified', category: 'Cardiovascular' },
  { code: 'I21.9', description: 'Acute myocardial infarction, unspecified', category: 'Cardiovascular' },
  { code: 'I25.10', description: 'Atherosclerotic heart disease of native coronary artery without angina pectoris', category: 'Cardiovascular' },
  { code: 'I25.9', description: 'Chronic ischemic heart disease, unspecified', category: 'Cardiovascular' },
  { code: 'I48.91', description: 'Unspecified atrial fibrillation', category: 'Cardiovascular' },
  { code: 'I48.92', description: 'Unspecified atrial flutter', category: 'Cardiovascular' },
  { code: 'I50.9', description: 'Heart failure, unspecified', category: 'Cardiovascular' },
  { code: 'I50.22', description: 'Chronic systolic (congestive) heart failure', category: 'Cardiovascular' },
  { code: 'I50.32', description: 'Chronic diastolic (congestive) heart failure', category: 'Cardiovascular' },
  { code: 'I63.9', description: 'Cerebral infarction, unspecified', category: 'Cardiovascular' },
  { code: 'I65.29', description: 'Occlusion and stenosis of unspecified carotid artery', category: 'Cardiovascular' },
  { code: 'I70.0', description: 'Atherosclerosis of aorta', category: 'Cardiovascular' },
  { code: 'I73.9', description: 'Peripheral vascular disease, unspecified', category: 'Cardiovascular' },
  { code: 'I80.10', description: 'Phlebitis and thrombophlebitis of unspecified femoral vein', category: 'Cardiovascular' },
  { code: 'I82.401', description: 'Acute embolism and thrombosis of unspecified deep veins of right lower extremity', category: 'Cardiovascular' },
  { code: 'I26.99', description: 'Other pulmonary embolism without acute cor pulmonale', category: 'Cardiovascular' },
  { code: 'I42.9', description: 'Cardiomyopathy, unspecified', category: 'Cardiovascular' },
  { code: 'I35.0', description: 'Nonrheumatic aortic (valve) stenosis', category: 'Cardiovascular' },

  // ===== Endocrine (18 codes) =====
  { code: 'E11.9', description: 'Type 2 diabetes mellitus without complications', category: 'Endocrine' },
  { code: 'E11.65', description: 'Type 2 diabetes mellitus with hyperglycemia', category: 'Endocrine' },
  { code: 'E11.40', description: 'Type 2 diabetes mellitus with diabetic neuropathy, unspecified', category: 'Endocrine' },
  { code: 'E11.21', description: 'Type 2 diabetes mellitus with diabetic nephropathy', category: 'Endocrine' },
  { code: 'E11.319', description: 'Type 2 diabetes mellitus with unspecified diabetic retinopathy without macular edema', category: 'Endocrine' },
  { code: 'E10.9', description: 'Type 1 diabetes mellitus without complications', category: 'Endocrine' },
  { code: 'E10.65', description: 'Type 1 diabetes mellitus with hyperglycemia', category: 'Endocrine' },
  { code: 'E03.9', description: 'Hypothyroidism, unspecified', category: 'Endocrine' },
  { code: 'E05.90', description: 'Thyrotoxicosis, unspecified without thyrotoxic crisis or storm', category: 'Endocrine' },
  { code: 'E06.3', description: 'Autoimmune thyroiditis', category: 'Endocrine' },
  { code: 'E04.1', description: 'Nontoxic single thyroid nodule', category: 'Endocrine' },
  { code: 'E66.01', description: 'Morbid (severe) obesity due to excess calories', category: 'Endocrine' },
  { code: 'E66.9', description: 'Obesity, unspecified', category: 'Endocrine' },
  { code: 'E78.5', description: 'Hyperlipidemia, unspecified', category: 'Endocrine' },
  { code: 'E78.00', description: 'Pure hypercholesterolemia, unspecified', category: 'Endocrine' },
  { code: 'E55.9', description: 'Vitamin D deficiency, unspecified', category: 'Endocrine' },
  { code: 'E87.6', description: 'Hypokalemia', category: 'Endocrine' },
  { code: 'E87.1', description: 'Hypo-osmolality and hyponatremia', category: 'Endocrine' },

  // ===== Respiratory (16 codes) =====
  { code: 'J06.9', description: 'Acute upper respiratory infection, unspecified', category: 'Respiratory' },
  { code: 'J18.9', description: 'Pneumonia, unspecified organism', category: 'Respiratory' },
  { code: 'J20.9', description: 'Acute bronchitis, unspecified', category: 'Respiratory' },
  { code: 'J44.1', description: 'Chronic obstructive pulmonary disease with (acute) exacerbation', category: 'Respiratory' },
  { code: 'J44.9', description: 'Chronic obstructive pulmonary disease, unspecified', category: 'Respiratory' },
  { code: 'J45.20', description: 'Mild intermittent asthma, uncomplicated', category: 'Respiratory' },
  { code: 'J45.40', description: 'Moderate persistent asthma, uncomplicated', category: 'Respiratory' },
  { code: 'J45.50', description: 'Severe persistent asthma, uncomplicated', category: 'Respiratory' },
  { code: 'J45.909', description: 'Unspecified asthma, uncomplicated', category: 'Respiratory' },
  { code: 'J30.9', description: 'Allergic rhinitis, unspecified', category: 'Respiratory' },
  { code: 'J32.9', description: 'Chronic sinusitis, unspecified', category: 'Respiratory' },
  { code: 'J01.90', description: 'Acute sinusitis, unspecified', category: 'Respiratory' },
  { code: 'J02.9', description: 'Acute pharyngitis, unspecified', category: 'Respiratory' },
  { code: 'J84.10', description: 'Pulmonary fibrosis, unspecified', category: 'Respiratory' },
  { code: 'J96.00', description: 'Acute respiratory failure, unspecified whether with hypoxia or hypercapnia', category: 'Respiratory' },
  { code: 'J43.9', description: 'Emphysema, unspecified', category: 'Respiratory' },

  // ===== Mental Health (18 codes) =====
  { code: 'F32.1', description: 'Major depressive disorder, single episode, moderate', category: 'Mental Health' },
  { code: 'F32.9', description: 'Major depressive disorder, single episode, unspecified', category: 'Mental Health' },
  { code: 'F33.0', description: 'Major depressive disorder, recurrent, mild', category: 'Mental Health' },
  { code: 'F33.1', description: 'Major depressive disorder, recurrent, moderate', category: 'Mental Health' },
  { code: 'F41.1', description: 'Generalized anxiety disorder', category: 'Mental Health' },
  { code: 'F41.0', description: 'Panic disorder without agoraphobia', category: 'Mental Health' },
  { code: 'F41.9', description: 'Anxiety disorder, unspecified', category: 'Mental Health' },
  { code: 'F43.10', description: 'Post-traumatic stress disorder, unspecified', category: 'Mental Health' },
  { code: 'F43.23', description: 'Adjustment disorder with mixed anxiety and depressed mood', category: 'Mental Health' },
  { code: 'F10.20', description: 'Alcohol dependence, uncomplicated', category: 'Mental Health' },
  { code: 'F10.10', description: 'Alcohol abuse, uncomplicated', category: 'Mental Health' },
  { code: 'F17.210', description: 'Nicotine dependence, cigarettes, uncomplicated', category: 'Mental Health' },
  { code: 'F11.20', description: 'Opioid dependence, uncomplicated', category: 'Mental Health' },
  { code: 'F31.9', description: 'Bipolar disorder, unspecified', category: 'Mental Health' },
  { code: 'F20.9', description: 'Schizophrenia, unspecified', category: 'Mental Health' },
  { code: 'F90.9', description: 'Attention-deficit hyperactivity disorder, unspecified type', category: 'Mental Health' },
  { code: 'F51.01', description: 'Primary insomnia', category: 'Mental Health' },
  { code: 'F42.9', description: 'Obsessive-compulsive disorder, unspecified', category: 'Mental Health' },

  // ===== Musculoskeletal (18 codes) =====
  { code: 'M54.5', description: 'Low back pain', category: 'Musculoskeletal' },
  { code: 'M54.2', description: 'Cervicalgia', category: 'Musculoskeletal' },
  { code: 'M79.3', description: 'Panniculitis, unspecified', category: 'Musculoskeletal' },
  { code: 'M25.511', description: 'Pain in right shoulder', category: 'Musculoskeletal' },
  { code: 'M25.561', description: 'Pain in right knee', category: 'Musculoskeletal' },
  { code: 'M17.9', description: 'Osteoarthritis of knee, unspecified', category: 'Musculoskeletal' },
  { code: 'M17.11', description: 'Primary osteoarthritis, right knee', category: 'Musculoskeletal' },
  { code: 'M16.9', description: 'Osteoarthritis of hip, unspecified', category: 'Musculoskeletal' },
  { code: 'M19.90', description: 'Unspecified osteoarthritis, unspecified site', category: 'Musculoskeletal' },
  { code: 'M81.0', description: 'Age-related osteoporosis without current pathological fracture', category: 'Musculoskeletal' },
  { code: 'M79.1', description: 'Myalgia', category: 'Musculoskeletal' },
  { code: 'M79.7', description: 'Fibromyalgia', category: 'Musculoskeletal' },
  { code: 'M06.9', description: 'Rheumatoid arthritis, unspecified', category: 'Musculoskeletal' },
  { code: 'M10.9', description: 'Gout, unspecified', category: 'Musculoskeletal' },
  { code: 'M51.16', description: 'Intervertebral disc disorders with radiculopathy, lumbar region', category: 'Musculoskeletal' },
  { code: 'M47.816', description: 'Spondylosis without myelopathy or radiculopathy, lumbar region', category: 'Musculoskeletal' },
  { code: 'M75.10', description: 'Unspecified rotator cuff tear or rupture of unspecified shoulder, not specified as traumatic', category: 'Musculoskeletal' },
  { code: 'M62.838', description: 'Other muscle spasm', category: 'Musculoskeletal' },

  // ===== Gastrointestinal (16 codes) =====
  { code: 'K21.0', description: 'Gastro-esophageal reflux disease with esophagitis', category: 'Gastrointestinal' },
  { code: 'K21.9', description: 'Gastro-esophageal reflux disease without esophagitis', category: 'Gastrointestinal' },
  { code: 'K29.70', description: 'Gastritis, unspecified, without bleeding', category: 'Gastrointestinal' },
  { code: 'K25.9', description: 'Gastric ulcer, unspecified as acute or chronic, without hemorrhage or perforation', category: 'Gastrointestinal' },
  { code: 'K58.9', description: 'Irritable bowel syndrome without diarrhea', category: 'Gastrointestinal' },
  { code: 'K50.90', description: 'Crohn\'s disease, unspecified, without complications', category: 'Gastrointestinal' },
  { code: 'K51.90', description: 'Ulcerative colitis, unspecified, without complications', category: 'Gastrointestinal' },
  { code: 'K57.30', description: 'Diverticulosis of large intestine without perforation or abscess without bleeding', category: 'Gastrointestinal' },
  { code: 'K80.20', description: 'Calculus of gallbladder without cholecystitis without obstruction', category: 'Gastrointestinal' },
  { code: 'K76.0', description: 'Fatty (change of) liver, not elsewhere classified', category: 'Gastrointestinal' },
  { code: 'K74.60', description: 'Unspecified cirrhosis of liver', category: 'Gastrointestinal' },
  { code: 'K85.90', description: 'Acute pancreatitis without necrosis or infection, unspecified', category: 'Gastrointestinal' },
  { code: 'K59.00', description: 'Constipation, unspecified', category: 'Gastrointestinal' },
  { code: 'K92.1', description: 'Melena', category: 'Gastrointestinal' },
  { code: 'K40.90', description: 'Unilateral inguinal hernia, without obstruction or gangrene, not specified as recurrent', category: 'Gastrointestinal' },
  { code: 'K62.5', description: 'Hemorrhage of anus and rectum', category: 'Gastrointestinal' },

  // ===== Neurological (16 codes) =====
  { code: 'G43.909', description: 'Migraine, unspecified, not intractable, without status migrainosus', category: 'Neurological' },
  { code: 'G43.009', description: 'Migraine without aura, not intractable, without status migrainosus', category: 'Neurological' },
  { code: 'G44.1', description: 'Vascular headache, not elsewhere classified', category: 'Neurological' },
  { code: 'R51.9', description: 'Headache, unspecified', category: 'Neurological' },
  { code: 'G40.909', description: 'Epilepsy, unspecified, not intractable, without status epilepticus', category: 'Neurological' },
  { code: 'G20', description: 'Parkinson\'s disease', category: 'Neurological' },
  { code: 'G30.9', description: 'Alzheimer\'s disease, unspecified', category: 'Neurological' },
  { code: 'G35', description: 'Multiple sclerosis', category: 'Neurological' },
  { code: 'G47.33', description: 'Obstructive sleep apnea', category: 'Neurological' },
  { code: 'G47.00', description: 'Insomnia, unspecified', category: 'Neurological' },
  { code: 'G62.9', description: 'Polyneuropathy, unspecified', category: 'Neurological' },
  { code: 'G56.00', description: 'Carpal tunnel syndrome, unspecified upper limb', category: 'Neurological' },
  { code: 'G89.29', description: 'Other chronic pain', category: 'Neurological' },
  { code: 'G89.4', description: 'Chronic pain syndrome', category: 'Neurological' },
  { code: 'G25.81', description: 'Restless legs syndrome', category: 'Neurological' },
  { code: 'R55', description: 'Syncope and collapse', category: 'Neurological' },

  // ===== Dermatological (12 codes) =====
  { code: 'L20.9', description: 'Atopic dermatitis, unspecified', category: 'Dermatological' },
  { code: 'L30.9', description: 'Dermatitis, unspecified', category: 'Dermatological' },
  { code: 'L40.0', description: 'Psoriasis vulgaris', category: 'Dermatological' },
  { code: 'L50.9', description: 'Urticaria, unspecified', category: 'Dermatological' },
  { code: 'L70.0', description: 'Acne vulgaris', category: 'Dermatological' },
  { code: 'L03.90', description: 'Cellulitis, unspecified', category: 'Dermatological' },
  { code: 'L08.9', description: 'Local infection of the skin and subcutaneous tissue, unspecified', category: 'Dermatological' },
  { code: 'B35.1', description: 'Tinea unguium', category: 'Dermatological' },
  { code: 'L82.1', description: 'Other seborrheic keratosis', category: 'Dermatological' },
  { code: 'D22.9', description: 'Melanocytic nevi, unspecified', category: 'Dermatological' },
  { code: 'L57.0', description: 'Actinic keratosis', category: 'Dermatological' },
  { code: 'L02.91', description: 'Cutaneous abscess, unspecified', category: 'Dermatological' },

  // ===== Genitourinary (14 codes) =====
  { code: 'N39.0', description: 'Urinary tract infection, site not specified', category: 'Genitourinary' },
  { code: 'N18.9', description: 'Chronic kidney disease, unspecified', category: 'Genitourinary' },
  { code: 'N18.3', description: 'Chronic kidney disease, stage 3 (moderate)', category: 'Genitourinary' },
  { code: 'N17.9', description: 'Acute kidney failure, unspecified', category: 'Genitourinary' },
  { code: 'N40.0', description: 'Benign prostatic hyperplasia without lower urinary tract symptoms', category: 'Genitourinary' },
  { code: 'N40.1', description: 'Benign prostatic hyperplasia with lower urinary tract symptoms', category: 'Genitourinary' },
  { code: 'N20.0', description: 'Calculus of kidney', category: 'Genitourinary' },
  { code: 'N80.0', description: 'Endometriosis of uterus', category: 'Genitourinary' },
  { code: 'N92.0', description: 'Excessive and frequent menstruation with regular cycle', category: 'Genitourinary' },
  { code: 'N95.1', description: 'Menopausal and female climacteric states', category: 'Genitourinary' },
  { code: 'N76.0', description: 'Acute vaginitis', category: 'Genitourinary' },
  { code: 'N30.00', description: 'Acute cystitis without hematuria', category: 'Genitourinary' },
  { code: 'R31.9', description: 'Hematuria, unspecified', category: 'Genitourinary' },
  { code: 'N13.30', description: 'Unspecified hydronephrosis', category: 'Genitourinary' },

  // ===== Infectious (16 codes) =====
  { code: 'A09', description: 'Infectious gastroenteritis and colitis, unspecified', category: 'Infectious' },
  { code: 'A41.9', description: 'Sepsis, unspecified organism', category: 'Infectious' },
  { code: 'A49.9', description: 'Bacterial infection, unspecified', category: 'Infectious' },
  { code: 'B34.9', description: 'Viral infection, unspecified', category: 'Infectious' },
  { code: 'B19.20', description: 'Unspecified viral hepatitis C without hepatic coma', category: 'Infectious' },
  { code: 'B20', description: 'Human immunodeficiency virus [HIV] disease', category: 'Infectious' },
  { code: 'J09.X2', description: 'Influenza due to identified novel influenza A virus with other respiratory manifestations', category: 'Infectious' },
  { code: 'J11.1', description: 'Influenza due to unidentified influenza virus with other respiratory manifestations', category: 'Infectious' },
  { code: 'U07.1', description: 'COVID-19', category: 'Infectious' },
  { code: 'B37.0', description: 'Candidal stomatitis', category: 'Infectious' },
  { code: 'A46', description: 'Erysipelas', category: 'Infectious' },
  { code: 'B02.9', description: 'Zoster without complications', category: 'Infectious' },
  { code: 'B00.9', description: 'Herpesviral infection, unspecified', category: 'Infectious' },
  { code: 'A04.72', description: 'Clostridioides difficile enterocolitis, recurrent', category: 'Infectious' },
  { code: 'L03.119', description: 'Cellulitis of unspecified part of limb', category: 'Infectious' },
  { code: 'J15.9', description: 'Unspecified bacterial pneumonia', category: 'Infectious' },

  // ===== Neoplasms (14 codes) =====
  { code: 'C50.919', description: 'Malignant neoplasm of unspecified site of unspecified female breast', category: 'Neoplasms' },
  { code: 'C34.90', description: 'Malignant neoplasm of unspecified part of unspecified bronchus or lung', category: 'Neoplasms' },
  { code: 'C61', description: 'Malignant neoplasm of prostate', category: 'Neoplasms' },
  { code: 'C18.9', description: 'Malignant neoplasm of colon, unspecified', category: 'Neoplasms' },
  { code: 'C43.9', description: 'Malignant melanoma of skin, unspecified', category: 'Neoplasms' },
  { code: 'C67.9', description: 'Malignant neoplasm of bladder, unspecified', category: 'Neoplasms' },
  { code: 'C73', description: 'Malignant neoplasm of thyroid gland', category: 'Neoplasms' },
  { code: 'C56.9', description: 'Malignant neoplasm of unspecified ovary', category: 'Neoplasms' },
  { code: 'C25.9', description: 'Malignant neoplasm of pancreas, unspecified', category: 'Neoplasms' },
  { code: 'C64.9', description: 'Malignant neoplasm of unspecified kidney, except renal pelvis', category: 'Neoplasms' },
  { code: 'D25.9', description: 'Leiomyoma of uterus, unspecified', category: 'Neoplasms' },
  { code: 'D17.9', description: 'Benign lipomatous neoplasm, unspecified', category: 'Neoplasms' },
  { code: 'C85.90', description: 'Non-Hodgkin lymphoma, unspecified, unspecified site', category: 'Neoplasms' },
  { code: 'C91.10', description: 'Chronic lymphocytic leukemia of B-cell type not having achieved remission', category: 'Neoplasms' },

  // ===== Hematological (10 codes) =====
  { code: 'D64.9', description: 'Anemia, unspecified', category: 'Hematological' },
  { code: 'D50.9', description: 'Iron deficiency anemia, unspecified', category: 'Hematological' },
  { code: 'D51.9', description: 'Vitamin B12 deficiency anemia, unspecified', category: 'Hematological' },
  { code: 'D69.6', description: 'Thrombocytopenia, unspecified', category: 'Hematological' },
  { code: 'D68.9', description: 'Coagulation defect, unspecified', category: 'Hematological' },
  { code: 'D72.829', description: 'Elevated white blood cell count, unspecified', category: 'Hematological' },
  { code: 'D70.9', description: 'Neutropenia, unspecified', category: 'Hematological' },
  { code: 'D75.1', description: 'Secondary polycythemia', category: 'Hematological' },
  { code: 'D57.1', description: 'Sickle-cell disease without crisis', category: 'Hematological' },
  { code: 'D56.9', description: 'Thalassemia, unspecified', category: 'Hematological' },

  // ===== Ophthalmological (10 codes) =====
  { code: 'H40.10X0', description: 'Unspecified open-angle glaucoma, stage unspecified', category: 'Ophthalmological' },
  { code: 'H25.9', description: 'Unspecified age-related cataract', category: 'Ophthalmological' },
  { code: 'H35.30', description: 'Unspecified macular degeneration', category: 'Ophthalmological' },
  { code: 'H10.9', description: 'Unspecified conjunctivitis', category: 'Ophthalmological' },
  { code: 'H52.4', description: 'Presbyopia', category: 'Ophthalmological' },
  { code: 'H52.13', description: 'Myopia, bilateral', category: 'Ophthalmological' },
  { code: 'H04.129', description: 'Dry eye syndrome of unspecified lacrimal gland', category: 'Ophthalmological' },
  { code: 'H36', description: 'Retinal disorders in diseases classified elsewhere', category: 'Ophthalmological' },
  { code: 'H53.9', description: 'Unspecified visual disturbance', category: 'Ophthalmological' },
  { code: 'H66.90', description: 'Otitis media, unspecified, unspecified ear', category: 'Ophthalmological' },

  // ===== Pediatric (10 codes) =====
  { code: 'J03.90', description: 'Acute tonsillitis, unspecified', category: 'Pediatric' },
  { code: 'H65.90', description: 'Unspecified nonsuppurative otitis media, unspecified ear', category: 'Pediatric' },
  { code: 'J21.9', description: 'Acute bronchiolitis, unspecified', category: 'Pediatric' },
  { code: 'B08.4', description: 'Enteroviral vesicular stomatitis with exanthem', category: 'Pediatric' },
  { code: 'B01.9', description: 'Varicella without complication', category: 'Pediatric' },
  { code: 'R62.51', description: 'Failure to thrive (child)', category: 'Pediatric' },
  { code: 'F80.9', description: 'Developmental disorder of speech and language, unspecified', category: 'Pediatric' },
  { code: 'F84.0', description: 'Autistic disorder', category: 'Pediatric' },
  { code: 'P07.39', description: 'Other preterm newborn, unspecified weeks of gestation', category: 'Pediatric' },
  { code: 'P59.9', description: 'Neonatal jaundice, unspecified', category: 'Pediatric' },

  // ===== General/Other (12 codes) =====
  { code: 'R10.9', description: 'Unspecified abdominal pain', category: 'General/Other' },
  { code: 'R50.9', description: 'Fever, unspecified', category: 'General/Other' },
  { code: 'R05.9', description: 'Cough, unspecified', category: 'General/Other' },
  { code: 'R53.83', description: 'Other fatigue', category: 'General/Other' },
  { code: 'R42', description: 'Dizziness and giddiness', category: 'General/Other' },
  { code: 'R00.0', description: 'Tachycardia, unspecified', category: 'General/Other' },
  { code: 'R06.00', description: 'Dyspnea, unspecified', category: 'General/Other' },
  { code: 'R73.03', description: 'Prediabetes', category: 'General/Other' },
  { code: 'Z23', description: 'Encounter for immunization', category: 'General/Other' },
  { code: 'Z00.00', description: 'Encounter for general adult medical examination without abnormal findings', category: 'General/Other' },
  { code: 'Z87.891', description: 'Personal history of nicotine dependence', category: 'General/Other' },
  { code: 'Z79.899', description: 'Other long term (current) drug therapy', category: 'General/Other' },
];
