export const labTests = [
  // ── Hematology (CBC Panel) ──────────────────────────────────────────
  {
    name: 'White Blood Cell Count (WBC)',
    category: 'Hematology',
    unit: '10^3/uL',
    normalRangeMin: 4.5,
    normalRangeMax: 11.0,
    normalRangeText: '4.5-11.0 x10^3/uL',
    sampleType: 'Blood',
  },
  {
    name: 'Red Blood Cell Count (RBC)',
    category: 'Hematology',
    unit: '10^6/uL',
    normalRangeMin: 4.2,
    normalRangeMax: 5.9,
    normalRangeText: '4.2-5.9 x10^6/uL',
    sampleType: 'Blood',
  },
  {
    name: 'Hemoglobin',
    category: 'Hematology',
    unit: 'g/dL',
    normalRangeMin: 12.0,
    normalRangeMax: 17.5,
    normalRangeText: '12.0-17.5 g/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Hematocrit',
    category: 'Hematology',
    unit: '%',
    normalRangeMin: 36.0,
    normalRangeMax: 51.0,
    normalRangeText: '36.0-51.0%',
    sampleType: 'Blood',
  },
  {
    name: 'Platelet Count',
    category: 'Hematology',
    unit: '10^3/uL',
    normalRangeMin: 150,
    normalRangeMax: 400,
    normalRangeText: '150-400 x10^3/uL',
    sampleType: 'Blood',
  },
  {
    name: 'Mean Corpuscular Volume (MCV)',
    category: 'Hematology',
    unit: 'fL',
    normalRangeMin: 80,
    normalRangeMax: 100,
    normalRangeText: '80-100 fL',
    sampleType: 'Blood',
  },
  {
    name: 'Mean Corpuscular Hemoglobin (MCH)',
    category: 'Hematology',
    unit: 'pg',
    normalRangeMin: 27,
    normalRangeMax: 33,
    normalRangeText: '27-33 pg',
    sampleType: 'Blood',
  },

  // ── Chemistry / Metabolic (CMP & BMP) ──────────────────────────────
  {
    name: 'Glucose, Fasting',
    category: 'Chemistry',
    unit: 'mg/dL',
    normalRangeMin: 70,
    normalRangeMax: 99,
    normalRangeText: '70-99 mg/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Blood Urea Nitrogen (BUN)',
    category: 'Chemistry',
    unit: 'mg/dL',
    normalRangeMin: 7,
    normalRangeMax: 20,
    normalRangeText: '7-20 mg/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Creatinine',
    category: 'Kidney Function',
    unit: 'mg/dL',
    normalRangeMin: 0.6,
    normalRangeMax: 1.2,
    normalRangeText: '0.6-1.2 mg/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Sodium',
    category: 'Chemistry',
    unit: 'mEq/L',
    normalRangeMin: 136,
    normalRangeMax: 145,
    normalRangeText: '136-145 mEq/L',
    sampleType: 'Blood',
  },
  {
    name: 'Potassium',
    category: 'Chemistry',
    unit: 'mEq/L',
    normalRangeMin: 3.5,
    normalRangeMax: 5.0,
    normalRangeText: '3.5-5.0 mEq/L',
    sampleType: 'Blood',
  },
  {
    name: 'Chloride',
    category: 'Chemistry',
    unit: 'mEq/L',
    normalRangeMin: 98,
    normalRangeMax: 106,
    normalRangeText: '98-106 mEq/L',
    sampleType: 'Blood',
  },
  {
    name: 'Carbon Dioxide (CO2)',
    category: 'Chemistry',
    unit: 'mEq/L',
    normalRangeMin: 23,
    normalRangeMax: 29,
    normalRangeText: '23-29 mEq/L',
    sampleType: 'Blood',
  },
  {
    name: 'Calcium',
    category: 'Chemistry',
    unit: 'mg/dL',
    normalRangeMin: 8.5,
    normalRangeMax: 10.5,
    normalRangeText: '8.5-10.5 mg/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Total Protein',
    category: 'Chemistry',
    unit: 'g/dL',
    normalRangeMin: 6.0,
    normalRangeMax: 8.3,
    normalRangeText: '6.0-8.3 g/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Albumin',
    category: 'Chemistry',
    unit: 'g/dL',
    normalRangeMin: 3.5,
    normalRangeMax: 5.5,
    normalRangeText: '3.5-5.5 g/dL',
    sampleType: 'Blood',
  },

  // ── Lipid Panel ─────────────────────────────────────────────────────
  {
    name: 'Total Cholesterol',
    category: 'Lipid Panel',
    unit: 'mg/dL',
    normalRangeMin: null,
    normalRangeMax: 200,
    normalRangeText: 'Desirable: <200 mg/dL',
    sampleType: 'Blood',
  },
  {
    name: 'LDL Cholesterol',
    category: 'Lipid Panel',
    unit: 'mg/dL',
    normalRangeMin: null,
    normalRangeMax: 100,
    normalRangeText: 'Optimal: <100 mg/dL',
    sampleType: 'Blood',
  },
  {
    name: 'HDL Cholesterol',
    category: 'Lipid Panel',
    unit: 'mg/dL',
    normalRangeMin: 40,
    normalRangeMax: null,
    normalRangeText: 'Desirable: >40 mg/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Triglycerides',
    category: 'Lipid Panel',
    unit: 'mg/dL',
    normalRangeMin: null,
    normalRangeMax: 150,
    normalRangeText: 'Normal: <150 mg/dL',
    sampleType: 'Blood',
  },

  // ── Liver Function ──────────────────────────────────────────────────
  {
    name: 'Alanine Aminotransferase (ALT)',
    category: 'Liver Function',
    unit: 'U/L',
    normalRangeMin: 7,
    normalRangeMax: 56,
    normalRangeText: '7-56 U/L',
    sampleType: 'Blood',
  },
  {
    name: 'Aspartate Aminotransferase (AST)',
    category: 'Liver Function',
    unit: 'U/L',
    normalRangeMin: 10,
    normalRangeMax: 40,
    normalRangeText: '10-40 U/L',
    sampleType: 'Blood',
  },
  {
    name: 'Alkaline Phosphatase (ALP)',
    category: 'Liver Function',
    unit: 'U/L',
    normalRangeMin: 44,
    normalRangeMax: 147,
    normalRangeText: '44-147 U/L',
    sampleType: 'Blood',
  },
  {
    name: 'Total Bilirubin',
    category: 'Liver Function',
    unit: 'mg/dL',
    normalRangeMin: 0.1,
    normalRangeMax: 1.2,
    normalRangeText: '0.1-1.2 mg/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Direct Bilirubin',
    category: 'Liver Function',
    unit: 'mg/dL',
    normalRangeMin: 0.0,
    normalRangeMax: 0.3,
    normalRangeText: '0.0-0.3 mg/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Gamma-Glutamyl Transferase (GGT)',
    category: 'Liver Function',
    unit: 'U/L',
    normalRangeMin: 9,
    normalRangeMax: 48,
    normalRangeText: '9-48 U/L',
    sampleType: 'Blood',
  },

  // ── Kidney Function ─────────────────────────────────────────────────
  {
    name: 'Estimated GFR (eGFR)',
    category: 'Kidney Function',
    unit: 'mL/min/1.73m2',
    normalRangeMin: 90,
    normalRangeMax: null,
    normalRangeText: 'Normal: >=90 mL/min/1.73m2',
    sampleType: 'Blood',
  },
  {
    name: 'Uric Acid',
    category: 'Kidney Function',
    unit: 'mg/dL',
    normalRangeMin: 2.4,
    normalRangeMax: 7.0,
    normalRangeText: '2.4-7.0 mg/dL',
    sampleType: 'Blood',
  },

  // ── Thyroid ─────────────────────────────────────────────────────────
  {
    name: 'Thyroid Stimulating Hormone (TSH)',
    category: 'Thyroid',
    unit: 'mIU/L',
    normalRangeMin: 0.4,
    normalRangeMax: 4.0,
    normalRangeText: '0.4-4.0 mIU/L',
    sampleType: 'Blood',
  },
  {
    name: 'Free T4 (Thyroxine)',
    category: 'Thyroid',
    unit: 'ng/dL',
    normalRangeMin: 0.8,
    normalRangeMax: 1.8,
    normalRangeText: '0.8-1.8 ng/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Free T3 (Triiodothyronine)',
    category: 'Thyroid',
    unit: 'pg/mL',
    normalRangeMin: 2.3,
    normalRangeMax: 4.2,
    normalRangeText: '2.3-4.2 pg/mL',
    sampleType: 'Blood',
  },

  // ── Diabetes ────────────────────────────────────────────────────────
  {
    name: 'Hemoglobin A1c (HbA1c)',
    category: 'Diabetes',
    unit: '%',
    normalRangeMin: null,
    normalRangeMax: 5.6,
    normalRangeText: 'Normal: <5.7%',
    sampleType: 'Blood',
  },
  {
    name: 'Insulin, Fasting',
    category: 'Diabetes',
    unit: 'uIU/mL',
    normalRangeMin: 2.6,
    normalRangeMax: 24.9,
    normalRangeText: '2.6-24.9 uIU/mL',
    sampleType: 'Blood',
  },

  // ── Coagulation ─────────────────────────────────────────────────────
  {
    name: 'Prothrombin Time (PT)',
    category: 'Coagulation',
    unit: 'seconds',
    normalRangeMin: 11.0,
    normalRangeMax: 13.5,
    normalRangeText: '11.0-13.5 seconds',
    sampleType: 'Blood',
  },
  {
    name: 'International Normalized Ratio (INR)',
    category: 'Coagulation',
    unit: '',
    normalRangeMin: 0.8,
    normalRangeMax: 1.1,
    normalRangeText: '0.8-1.1',
    sampleType: 'Blood',
  },
  {
    name: 'Partial Thromboplastin Time (PTT)',
    category: 'Coagulation',
    unit: 'seconds',
    normalRangeMin: 25,
    normalRangeMax: 35,
    normalRangeText: '25-35 seconds',
    sampleType: 'Blood',
  },
  {
    name: 'D-Dimer',
    category: 'Coagulation',
    unit: 'ng/mL',
    normalRangeMin: null,
    normalRangeMax: 500,
    normalRangeText: 'Normal: <500 ng/mL',
    sampleType: 'Blood',
  },

  // ── Cardiac ─────────────────────────────────────────────────────────
  {
    name: 'Troponin I',
    category: 'Cardiac',
    unit: 'ng/mL',
    normalRangeMin: null,
    normalRangeMax: 0.04,
    normalRangeText: 'Normal: <0.04 ng/mL',
    sampleType: 'Blood',
  },
  {
    name: 'B-type Natriuretic Peptide (BNP)',
    category: 'Cardiac',
    unit: 'pg/mL',
    normalRangeMin: null,
    normalRangeMax: 100,
    normalRangeText: 'Normal: <100 pg/mL',
    sampleType: 'Blood',
  },
  {
    name: 'Creatine Kinase (CK)',
    category: 'Cardiac',
    unit: 'U/L',
    normalRangeMin: 22,
    normalRangeMax: 198,
    normalRangeText: '22-198 U/L',
    sampleType: 'Blood',
  },

  // ── Inflammatory ────────────────────────────────────────────────────
  {
    name: 'C-Reactive Protein (CRP)',
    category: 'Inflammatory',
    unit: 'mg/L',
    normalRangeMin: null,
    normalRangeMax: 3.0,
    normalRangeText: 'Normal: <3.0 mg/L',
    sampleType: 'Blood',
  },
  {
    name: 'Erythrocyte Sedimentation Rate (ESR)',
    category: 'Inflammatory',
    unit: 'mm/hr',
    normalRangeMin: 0,
    normalRangeMax: 20,
    normalRangeText: '0-20 mm/hr',
    sampleType: 'Blood',
  },
  {
    name: 'Ferritin',
    category: 'Inflammatory',
    unit: 'ng/mL',
    normalRangeMin: 12,
    normalRangeMax: 300,
    normalRangeText: '12-300 ng/mL',
    sampleType: 'Blood',
  },

  // ── Vitamins / Minerals ─────────────────────────────────────────────
  {
    name: 'Vitamin D, 25-Hydroxy',
    category: 'Vitamins/Minerals',
    unit: 'ng/mL',
    normalRangeMin: 30,
    normalRangeMax: 100,
    normalRangeText: '30-100 ng/mL',
    sampleType: 'Blood',
  },
  {
    name: 'Vitamin B12',
    category: 'Vitamins/Minerals',
    unit: 'pg/mL',
    normalRangeMin: 200,
    normalRangeMax: 900,
    normalRangeText: '200-900 pg/mL',
    sampleType: 'Blood',
  },
  {
    name: 'Folate',
    category: 'Vitamins/Minerals',
    unit: 'ng/mL',
    normalRangeMin: 2.7,
    normalRangeMax: 17.0,
    normalRangeText: '2.7-17.0 ng/mL',
    sampleType: 'Blood',
  },
  {
    name: 'Iron, Serum',
    category: 'Vitamins/Minerals',
    unit: 'ug/dL',
    normalRangeMin: 60,
    normalRangeMax: 170,
    normalRangeText: '60-170 ug/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Magnesium',
    category: 'Vitamins/Minerals',
    unit: 'mg/dL',
    normalRangeMin: 1.7,
    normalRangeMax: 2.2,
    normalRangeText: '1.7-2.2 mg/dL',
    sampleType: 'Blood',
  },
  {
    name: 'Phosphorus',
    category: 'Vitamins/Minerals',
    unit: 'mg/dL',
    normalRangeMin: 2.5,
    normalRangeMax: 4.5,
    normalRangeText: '2.5-4.5 mg/dL',
    sampleType: 'Blood',
  },

  // ── Urinalysis ──────────────────────────────────────────────────────
  {
    name: 'Urine pH',
    category: 'Urinalysis',
    unit: '',
    normalRangeMin: 4.5,
    normalRangeMax: 8.0,
    normalRangeText: '4.5-8.0',
    sampleType: 'Urine',
  },
  {
    name: 'Urine Specific Gravity',
    category: 'Urinalysis',
    unit: '',
    normalRangeMin: 1.005,
    normalRangeMax: 1.030,
    normalRangeText: '1.005-1.030',
    sampleType: 'Urine',
  },
  {
    name: 'Urine Protein',
    category: 'Urinalysis',
    unit: 'mg/dL',
    normalRangeMin: null,
    normalRangeMax: null,
    normalRangeText: 'Negative',
    sampleType: 'Urine',
  },
  {
    name: 'Urine Glucose',
    category: 'Urinalysis',
    unit: 'mg/dL',
    normalRangeMin: null,
    normalRangeMax: null,
    normalRangeText: 'Negative',
    sampleType: 'Urine',
  },
  {
    name: 'Urine Microalbumin',
    category: 'Urinalysis',
    unit: 'mg/L',
    normalRangeMin: null,
    normalRangeMax: 30,
    normalRangeText: 'Normal: <30 mg/L',
    sampleType: 'Urine',
  },

  // ── Infectious Disease ──────────────────────────────────────────────
  {
    name: 'HIV 1/2 Antigen/Antibody',
    category: 'Infectious Disease',
    unit: '',
    normalRangeMin: null,
    normalRangeMax: null,
    normalRangeText: 'Non-reactive',
    sampleType: 'Blood',
  },
  {
    name: 'Hepatitis B Surface Antigen (HBsAg)',
    category: 'Infectious Disease',
    unit: '',
    normalRangeMin: null,
    normalRangeMax: null,
    normalRangeText: 'Non-reactive',
    sampleType: 'Blood',
  },
  {
    name: 'Hepatitis C Antibody',
    category: 'Infectious Disease',
    unit: '',
    normalRangeMin: null,
    normalRangeMax: null,
    normalRangeText: 'Non-reactive',
    sampleType: 'Blood',
  },
  {
    name: 'Rapid Plasma Reagin (RPR)',
    category: 'Infectious Disease',
    unit: '',
    normalRangeMin: null,
    normalRangeMax: null,
    normalRangeText: 'Non-reactive',
    sampleType: 'Blood',
  },
];
