export const specialties = [
  {
    name: 'General Medicine',
    description: 'Primary care and internal medicine',
    icon: 'stethoscope',
    fields: [
      { fieldName: 'Chief Complaint', fieldType: 'TEXT', isRequired: true, sortOrder: 1 },
      { fieldName: 'History of Present Illness', fieldType: 'TEXTAREA', isRequired: true, sortOrder: 2 },
      { fieldName: 'Review of Systems', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 3 },
      { fieldName: 'Smoking Status', fieldType: 'SELECT', options: ['Never', 'Former', 'Current'], isRequired: false, sortOrder: 4 },
      { fieldName: 'Alcohol Use', fieldType: 'SELECT', options: ['None', 'Social', 'Moderate', 'Heavy'], isRequired: false, sortOrder: 5 },
    ],
  },
  {
    name: 'Cardiology',
    description: 'Heart and cardiovascular system',
    icon: 'heart-pulse',
    fields: [
      { fieldName: 'ECG Findings', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 1 },
      { fieldName: 'Echo Findings', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 2 },
      { fieldName: 'Stress Test Results', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 3 },
      { fieldName: 'NYHA Classification', fieldType: 'SELECT', options: ['Class I', 'Class II', 'Class III', 'Class IV'], isRequired: false, sortOrder: 4 },
      { fieldName: 'Cardiac Risk Score', fieldType: 'NUMBER', isRequired: false, sortOrder: 5 },
      { fieldName: 'Ejection Fraction (%)', fieldType: 'NUMBER', isRequired: false, sortOrder: 6 },
      { fieldName: 'Chest Pain Type', fieldType: 'SELECT', options: ['Typical Angina', 'Atypical Angina', 'Non-Anginal', 'Asymptomatic'], isRequired: false, sortOrder: 7 },
    ],
  },
  {
    name: 'Psychiatry',
    description: 'Mental health and behavioral disorders',
    icon: 'brain',
    fields: [
      { fieldName: 'Mental Status Exam', fieldType: 'TEXTAREA', isRequired: true, sortOrder: 1 },
      { fieldName: 'PHQ-9 Score', fieldType: 'NUMBER', isRequired: false, sortOrder: 2 },
      { fieldName: 'GAD-7 Score', fieldType: 'NUMBER', isRequired: false, sortOrder: 3 },
      { fieldName: 'Mood', fieldType: 'SELECT', options: ['Euthymic', 'Depressed', 'Elevated', 'Irritable', 'Anxious', 'Labile'], isRequired: true, sortOrder: 4 },
      { fieldName: 'Affect', fieldType: 'SELECT', options: ['Appropriate', 'Flat', 'Blunted', 'Restricted', 'Labile', 'Incongruent'], isRequired: true, sortOrder: 5 },
      { fieldName: 'Suicidal Ideation', fieldType: 'BOOLEAN', isRequired: true, sortOrder: 6 },
      { fieldName: 'Homicidal Ideation', fieldType: 'BOOLEAN', isRequired: true, sortOrder: 7 },
      { fieldName: 'Sleep Quality', fieldType: 'SELECT', options: ['Good', 'Fair', 'Poor', 'Insomnia'], isRequired: false, sortOrder: 8 },
      { fieldName: 'Risk Assessment Notes', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 9 },
    ],
  },
  {
    name: 'Pediatrics',
    description: 'Children and adolescent medicine',
    icon: 'baby',
    fields: [
      { fieldName: 'Birth Weight (kg)', fieldType: 'NUMBER', isRequired: false, sortOrder: 1 },
      { fieldName: 'Gestational Age (weeks)', fieldType: 'NUMBER', isRequired: false, sortOrder: 2 },
      { fieldName: 'Feeding Type', fieldType: 'SELECT', options: ['Breastfeeding', 'Formula', 'Mixed', 'Solid Foods'], isRequired: false, sortOrder: 3 },
      { fieldName: 'Developmental Milestones', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 4 },
      { fieldName: 'Vaccination Status', fieldType: 'SELECT', options: ['Up to Date', 'Behind Schedule', 'Unvaccinated', 'Partial'], isRequired: true, sortOrder: 5 },
      { fieldName: 'Growth Percentile - Weight', fieldType: 'NUMBER', isRequired: false, sortOrder: 6 },
      { fieldName: 'Growth Percentile - Height', fieldType: 'NUMBER', isRequired: false, sortOrder: 7 },
      { fieldName: 'Growth Percentile - Head Circumference', fieldType: 'NUMBER', isRequired: false, sortOrder: 8 },
    ],
  },
  {
    name: 'Orthopedics',
    description: 'Musculoskeletal system and injuries',
    icon: 'bone',
    fields: [
      { fieldName: 'Injury Location', fieldType: 'TEXT', isRequired: true, sortOrder: 1 },
      { fieldName: 'Injury Mechanism', fieldType: 'SELECT', options: ['Trauma', 'Overuse', 'Degenerative', 'Sports', 'Fall', 'Other'], isRequired: false, sortOrder: 2 },
      { fieldName: 'Pain Scale (0-10)', fieldType: 'NUMBER', isRequired: true, sortOrder: 3 },
      { fieldName: 'Range of Motion', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 4 },
      { fieldName: 'Imaging Findings', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 5 },
      { fieldName: 'Fracture Type', fieldType: 'SELECT', options: ['None', 'Simple', 'Compound', 'Comminuted', 'Stress', 'Pathological'], isRequired: false, sortOrder: 6 },
      { fieldName: 'Weight Bearing Status', fieldType: 'SELECT', options: ['Full', 'Partial', 'Non-Weight Bearing', 'Touch Down'], isRequired: false, sortOrder: 7 },
    ],
  },
  {
    name: 'Dermatology',
    description: 'Skin, hair, and nail conditions',
    icon: 'scan',
    fields: [
      { fieldName: 'Lesion Location', fieldType: 'TEXT', isRequired: true, sortOrder: 1 },
      { fieldName: 'Lesion Type', fieldType: 'SELECT', options: ['Macule', 'Papule', 'Plaque', 'Nodule', 'Vesicle', 'Pustule', 'Ulcer', 'Patch', 'Other'], isRequired: true, sortOrder: 2 },
      { fieldName: 'Lesion Size (cm)', fieldType: 'TEXT', isRequired: false, sortOrder: 3 },
      { fieldName: 'Duration', fieldType: 'TEXT', isRequired: false, sortOrder: 4 },
      { fieldName: 'Distribution', fieldType: 'SELECT', options: ['Localized', 'Generalized', 'Dermatomal', 'Bilateral', 'Sun-Exposed'], isRequired: false, sortOrder: 5 },
      { fieldName: 'Skin Biopsy Results', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 6 },
      { fieldName: 'Body Map Notes', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 7 },
    ],
  },
  {
    name: 'Ophthalmology',
    description: 'Eye and vision care',
    icon: 'eye',
    fields: [
      { fieldName: 'Visual Acuity - Right', fieldType: 'TEXT', isRequired: true, sortOrder: 1 },
      { fieldName: 'Visual Acuity - Left', fieldType: 'TEXT', isRequired: true, sortOrder: 2 },
      { fieldName: 'Intraocular Pressure - Right (mmHg)', fieldType: 'NUMBER', isRequired: false, sortOrder: 3 },
      { fieldName: 'Intraocular Pressure - Left (mmHg)', fieldType: 'NUMBER', isRequired: false, sortOrder: 4 },
      { fieldName: 'Fundoscopy Findings', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 5 },
      { fieldName: 'Slit Lamp Findings', fieldType: 'TEXTAREA', isRequired: false, sortOrder: 6 },
      { fieldName: 'Color Vision', fieldType: 'SELECT', options: ['Normal', 'Deficient', 'Not Tested'], isRequired: false, sortOrder: 7 },
    ],
  },
];

export const defaultServicePrices = [
  { name: 'General Consultation', category: 'CONSULTATION', price: 150, specialtyName: 'General Medicine' },
  { name: 'Specialist Consultation', category: 'CONSULTATION', price: 250, specialtyName: 'Cardiology' },
  { name: 'Psychiatry Consultation', category: 'CONSULTATION', price: 200, specialtyName: 'Psychiatry' },
  { name: 'Pediatric Consultation', category: 'CONSULTATION', price: 175, specialtyName: 'Pediatrics' },
  { name: 'Orthopedic Consultation', category: 'CONSULTATION', price: 250, specialtyName: 'Orthopedics' },
  { name: 'Dermatology Consultation', category: 'CONSULTATION', price: 200, specialtyName: 'Dermatology' },
  { name: 'Eye Examination', category: 'CONSULTATION', price: 200, specialtyName: 'Ophthalmology' },
  { name: 'Follow-up Visit', category: 'CONSULTATION', price: 100, specialtyName: null },
  { name: 'Emergency Visit', category: 'CONSULTATION', price: 350, specialtyName: null },
  { name: 'ECG', category: 'PROCEDURE', price: 75, specialtyName: 'Cardiology' },
  { name: 'Echocardiogram', category: 'PROCEDURE', price: 500, specialtyName: 'Cardiology' },
  { name: 'X-Ray', category: 'PROCEDURE', price: 120, specialtyName: null },
  { name: 'Cast Application', category: 'PROCEDURE', price: 300, specialtyName: 'Orthopedics' },
  { name: 'Skin Biopsy', category: 'PROCEDURE', price: 250, specialtyName: 'Dermatology' },
  { name: 'Wound Dressing', category: 'PROCEDURE', price: 50, specialtyName: null },
  { name: 'Minor Surgery', category: 'PROCEDURE', price: 500, specialtyName: null },
  { name: 'Blood Draw', category: 'LAB_TEST', price: 25, specialtyName: null },
  { name: 'Urinalysis', category: 'LAB_TEST', price: 30, specialtyName: null },
  { name: 'Complete Blood Count', category: 'LAB_TEST', price: 45, specialtyName: null },
  { name: 'Comprehensive Metabolic Panel', category: 'LAB_TEST', price: 65, specialtyName: null },
];

export const defaultClinicSettings = [
  { key: 'clinic_name', value: 'MedPulse Medical Center', group: 'general' },
  { key: 'clinic_address', value: '123 Healthcare Avenue, Medical District', group: 'general' },
  { key: 'clinic_city', value: 'New York', group: 'general' },
  { key: 'clinic_state', value: 'NY', group: 'general' },
  { key: 'clinic_zip', value: '10001', group: 'general' },
  { key: 'clinic_phone', value: '+1 (555) 123-4567', group: 'general' },
  { key: 'clinic_email', value: 'info@medpulse.com', group: 'general' },
  { key: 'clinic_website', value: 'https://medpulse.com', group: 'general' },
  { key: 'clinic_logo', value: '', group: 'general' },
  { key: 'working_hours_start', value: '08:00', group: 'schedule' },
  { key: 'working_hours_end', value: '18:00', group: 'schedule' },
  { key: 'working_days', value: 'Mon,Tue,Wed,Thu,Fri', group: 'schedule' },
  { key: 'appointment_duration', value: '30', group: 'schedule' },
  { key: 'appointment_buffer', value: '5', group: 'schedule' },
  { key: 'tax_rate', value: '0', group: 'billing' },
  { key: 'currency', value: 'USD', group: 'billing' },
  { key: 'invoice_prefix', value: 'INV', group: 'billing' },
  { key: 'invoice_footer', value: 'Thank you for choosing MedPulse Medical Center.', group: 'billing' },
  { key: 'reminder_hours_before', value: '24', group: 'notifications' },
  { key: 'enable_sms_reminders', value: 'false', group: 'notifications' },
  { key: 'enable_email_reminders', value: 'true', group: 'notifications' },
  { key: 'prescription_header', value: 'MedPulse Medical Center - Prescription', group: 'printing' },
  { key: 'prescription_footer', value: 'This prescription is valid for 30 days from issue date.', group: 'printing' },
];

export const defaultTemplates = [
  {
    name: 'General Checkup',
    specialtyName: 'General Medicine',
    isDefault: true,
    fields: {
      subjective: 'Patient presents for routine checkup.\n\nChief Complaint: \nHistory of Present Illness: \nPast Medical History: \nMedications: \nAllergies: ',
      objective: 'General: \nHEENT: \nCardiovascular: \nRespiratory: \nAbdominal: \nExtremities: \nNeurological: ',
      assessment: '',
      plan: '',
    },
  },
  {
    name: 'Cardiac Evaluation',
    specialtyName: 'Cardiology',
    isDefault: true,
    fields: {
      subjective: 'Patient presents for cardiac evaluation.\n\nChief Complaint: \nChest Pain: (character, location, duration, radiation, aggravating/relieving factors)\nDyspnea: \nPalpitations: \nSyncope/Pre-syncope: \nEdema: \nCardiac Risk Factors: ',
      objective: 'Vital Signs: \nCardiovascular: Heart sounds, murmurs, JVD\nRespiratory: \nExtremities: Edema, pulses\nECG: \nEchocardiogram: ',
      assessment: '',
      plan: '',
    },
  },
  {
    name: 'Psychiatric Assessment',
    specialtyName: 'Psychiatry',
    isDefault: true,
    fields: {
      subjective: 'Patient presents for psychiatric evaluation.\n\nChief Complaint: \nHistory of Present Illness: \nPsychiatric History: \nSubstance Use History: \nFamily Psychiatric History: \nSocial History: ',
      objective: 'Mental Status Examination:\nAppearance: \nBehavior: \nSpeech: \nMood: \nAffect: \nThought Process: \nThought Content: \nPerceptions: \nCognition: \nInsight: \nJudgment: ',
      assessment: '',
      plan: '',
    },
  },
  {
    name: 'Pediatric Well-Child Visit',
    specialtyName: 'Pediatrics',
    isDefault: true,
    fields: {
      subjective: 'Well-child visit.\n\nParent Concerns: \nFeeding/Nutrition: \nSleep Pattern: \nDevelopmental Progress: \nImmunization Status: \nSchool Performance: ',
      objective: 'Growth Parameters:\nWeight: (percentile)\nHeight: (percentile)\nHead Circumference: (percentile)\nBMI: (percentile)\n\nPhysical Exam:\nGeneral: \nHEENT: \nCardiovascular: \nRespiratory: \nAbdominal: \nMusculoskeletal: \nNeurological: \nSkin: \n\nDevelopmental Assessment: ',
      assessment: '',
      plan: '',
    },
  },
  {
    name: 'Orthopedic Assessment',
    specialtyName: 'Orthopedics',
    isDefault: true,
    fields: {
      subjective: 'Patient presents for orthopedic evaluation.\n\nChief Complaint: \nInjury Mechanism: \nPain Location: \nPain Character: \nPain Scale (0-10): \nFunctional Limitations: \nPrior Treatments: ',
      objective: 'Inspection: \nPalpation: \nRange of Motion: \nStrength Testing: \nSpecial Tests: \nNeurovascular Status: \nImaging Review: ',
      assessment: '',
      plan: '',
    },
  },
  {
    name: 'Dermatology Exam',
    specialtyName: 'Dermatology',
    isDefault: true,
    fields: {
      subjective: 'Patient presents for dermatological evaluation.\n\nChief Complaint: \nOnset/Duration: \nLocation: \nSymptoms (itching, burning, pain): \nPrevious Treatments: \nSkin Care Routine: \nSun Exposure: ',
      objective: 'Skin Exam:\nLesion Type: \nLocation: \nSize: \nColor: \nBorders: \nDistribution: \nSecondary Changes: \n\nDermoscopy: \nWood Lamp: ',
      assessment: '',
      plan: '',
    },
  },
  {
    name: 'Eye Examination',
    specialtyName: 'Ophthalmology',
    isDefault: true,
    fields: {
      subjective: 'Patient presents for eye examination.\n\nChief Complaint: \nVision Changes: \nEye Pain: \nRedness: \nDischarge: \nFlashes/Floaters: \nOcular History: \nFamily Eye History: ',
      objective: 'Visual Acuity:\nOD (Right): \nOS (Left): \nOU (Both): \n\nPupils: \nEOM: \nConfrontation Fields: \nSlit Lamp:\nLids/Lashes: \nConjunctiva: \nCornea: \nAnterior Chamber: \nIris: \nLens: \n\nIOP: OD: OS: \n\nDilated Fundus:\nOptic Disc: \nMacula: \nVessels: \nPeriphery: ',
      assessment: '',
      plan: '',
    },
  },
];
